### ISSUE TITLE
afterglow.getPlayer('myvideo').play() do the scroll action

### ISSUE THREAD

**Issue by romzes2** [moay/afterglow#101]
Hi,

The video on my web page, should start once it become at user view (by scrolling), I wrote the JQuery code and noticed that once I call afterglow.getPlayer('myvideo').play() the page make a scroll to the video. I decided first that problem in my code but after found the same issue on your demo page.

I also tested on chrome without plugins - same issue. And it apears only if video is not started yet.
Video with issue: https://romka.lv/bug.mp4

Before event:
![image](https://user-images.githubusercontent.com/10059282/68223624-cc3b0080-fff5-11e9-8942-c44b9a74ac76.png)

After: 
![image](https://user-images.githubusercontent.com/10059282/68223727-fc829f00-fff5-11e9-8228-0914c411ca1b.png)

The problem is significant, if I fire event on another page section.

**Comment by moay** [comment]
There are multiple possible reasons for this behaviour.

- This might be a "problem" of modern browsers. Browsers want to help users not to be bugged with some random video or audio being played to them without them knowing where it happens. So they make sure that the video is in the video whenever some script willingly starts playback without prior user interaction. Make sure to bind your play action to some sort of user induced event (like a click) and to not decouple the steps on your script side.
- It might be default behaviour by video.js. I currently don't have the time to investigate for multiple reasons (v1 is not the focus, I don't have enough time, etc.), but feel free to check that.

Also keep in mind that autoplay is bad user experience and does probably not work on mobile devices.

This doesn't seem like a technical issue based on a bug in the code, but feel free to reopen the issue if you think otherwise.

**Comment by romzes2** [comment]
I checked and seems the reason is video.js, at least most probably something there.

Maybe some one will help my advice at current moment:
```
<video **autoplay="autoplay"** class="afterglow" **data-volume="0"** height="1040" id="UNIQUE_VIDEO_ID" loop="loop" preload="auto" src="test.mp4" width="1918">Ups, something goes wrong! Here should be the video</video>
```

The trick is enabling autoplay and then pausing all players at page loading. In such scenario, the scroll effect will be disappear once you will call play action.

My current problem is that:
```
$(document).ready(function(){
	afterglow.getPlayer("UNIQUE_VIDEO_ID").pause();
 });
```
or 
```
$( ".afterglow" ).each(function( index ) {
	afterglow.on($(this).attr("id"), 'ready', function(){
		afterglow.getPlayer($(this).attr("id")).pause();
	});
});
```
Cause afterglow.getPlayer(...).pause is not a function. 
Not fount the event yet, how to solve this error in console.
