### ISSUE TITLE
Subtitles for Youtube videos

### ISSUE THREAD

**Issue by gama41** [moay/afterglow#15]
Hello, 

Is it possible to add the subtitles option in your next version please ?
It will be very useful.

**Comment by moay** [comment]
Hey @gama41,

thanks for the input. Subtitles are actually already possible. We won't officially support this feature, because it is quite unstable and some browsers don't even support it at all. But I can write a quick how-to tomorrow.

Could you create a new thread in the [community](https://community.afterglowplayer.com)? (Should be back online again). Thanks!

**Comment by moay** [comment]
Closed with this discussion: https://community.afterglowplayer.com/d/22-subtitles-for-youtube-videos
