### ISSUE TITLE
Fullscreen via double click?

### ISSUE THREAD

**Issue by fiedl** [moay/afterglow#27]
Is it possible to configure afterglow such that **double-clicking the video activates fullscreen** mode? I haven't found something like this in the [documentation](http://docs.afterglowplayer.com), yet.

Even better would be to have a configuration parameter that decides whether double click activates fullscreen or lightbox.

Something like this:

``` html
<video class="afterglow" id="myvideo" width="1280" height="720" 
  data-double-click="fullscreen">

  <source type="video/mp4" src="/path/to/myvideo.mp4" />
</video>
```

Thanks for the awesome project!

**Comment by moay** [comment]
Hi @fiedl,

sorry, I have been out of office for the last days. 

Yes, fullscreen via double click should be possible. This is a nice feature, I'll add it to the list.

The configuration parameter would be hard to implement. The lightbox works in a manner that would make this like really hard and not good looking. In order to open a playing video in a lightbox, afterglow'd need to stop the current video, clone it's base element, push it to the lightbox, initiate the player again, load the correct playback time and play. This would look like a big mess and take nearly a second, I guess.

So fullscreen: yes, lightbox: rather no...

**Comment by moay** [comment]
Done, comes with the next release. Will be default, for now no way to disable it (until someone needs it... ;-) )

**Comment by fiedl** [comment]
Thanks!
