### ISSUE TITLE
How to use API with lightbox setup?

### ISSUE THREAD

**Issue by beausmith** [moay/afterglow#30]
How is it possible to access the API methods with lightbox setup?

If it is possible, please modify this CodePen to show how:
https://codepen.io/beau/pen/ad4101aa2065775d4bba0cfc71e7e06d/

If not, adding the ability to access the API when playing videos in the lightbox would be stellar!

**Comment by moay** [comment]
I'll have a look into this, gimme a few hours...

**Comment by moay** [comment]
As far as I can see, there are two problems that prevent this from working.

1) There is a timing problem. When you try to access afterglow, it is not yet initiated. That is not such a big problem, as you can wait for that to happen.

2) The video player does not kick in at the time when afterglow is initiated. It will be created when you open the lightbox. So the event should be bound whenever you open the lightbox. This is a problem, because there is (until now) no way to make this happen. So we'll need to make one.

I'll give it a shot!

**Comment by beausmith** [comment]
Rock on!

**Comment by Kzip** [comment]
Has there been any update on this? I'm still running into timing issues, I tried to bind an event (clicking on the anchor tag related to the lightbox) and running afterglow.init and seeing if that could work but I still can't do a redirect after a video finishes playing.

**Comment by beausmith** [comment]
@Kzip - I gave up and used another library. Sorry, I forget which library I switched to.

**Comment by moay** [comment]
Don't know if anybody is still on this. We do now (with v1.0) have a working event system, which solves the issue. You can (with v1.0, as soon as it is publicly available) now react to the afterglow events, which will also fire for lightboxes.

So, for instance:

    afterglow.on('myplayerid', 'ended', function(){
        doSomething();
    });

will execute `doSomething()` when the clip ended. Use the 'lightbox-closed' event for when the lightbox closes.

Please be aware that this wont work prior to v1.0.0b1. Let me know if there are any problems.
