### ISSUE TITLE
Provide an un-compressed version

### ISSUE THREAD

**Issue by micr0lab** [moay/afterglow#52]
This is a feature request.

Could you provide a un-compressed version of your tool (i.e., of your `js` file), to allow easier edition and study of your code.

**Comment by moay** [comment]
Go ahead and download the sources. We won't provide an uncompressed version of the final release for two reasons:

- It is not useful at all, because the real coding will never happen in such a file. The released file is completely compiled and does not exist before the release.
- It's of no use in real world usage.

You should look into the sources in the `src` folders, everything you need is there. Also, you should take a look at this page: http://docs.afterglowplayer.com/docs/build-your-own
