### ISSUE TITLE
How to disable controls?

### ISSUE THREAD

**Issue by sevenuz** [moay/afterglow#54]
How I can disable controls of the player? The controls flag on the video element doesn't work and there is no option for that in the docs.
Thx:) beautyful player

**Comment by moay** [comment]
Hi. :-) There is no option because it's just not possible. It's a feature of html5 video which you can use without anything but is ignored by afterglow because it is basically only a set of beatiful controls.

Use something like that:

```html
<video src="something.mp4" autoplay="autoplay"></video>
```

As long as there is no `controls` attribute, you won't see any.
