### ISSUE TITLE
New event playback-started

### ISSUE THREAD

**Issue by DoraPaula** [moay/afterglow#58]
I would like to access the duration of a video started in a lightbox. That's what I've tried:

```
<!DOCTYPE html>
<html>
  <head>
    <title>afterglow player</title>
    <script src="../afterglow.min.js"></script>
    <script>
        afterglow.on('myvideo', "ready", function(event) {
                /* this works fine: */
                //alert(event.playerid);

                /* this delivers zero: */
                alert(event.player.duration());
        });
    </script>
  </head>
  <body>
    <a class="afterglow" href="#myvideo">
        Launch lightbox
    </a>
    <video id="myvideo" width="960" height="540">
      <source type="video/mp4" src="test.mp4" />
    </video>
  </body>
<html>
```

I'm new to javascript and afterglow, thus my questions:
Why is the duration information not available in ready-state?
What am I doing wrong?

Thanks a lot for your fantastic work!

**Comment by moay** [comment]
Hi there,

the problem is probably related to the loading of your video. When afterglow (or video.js, actually) fires the `ready` event, the video in the lightbox is not loaded yet. This is due to the inner workings of the HTML5 video tag. The video will not be loaded until it is played, so when afterglow is ready, the next step is to start the video. So on `ready`, the video has not been loaded and the duration cannot be determined.

There is one workaround for this though. You could subscribe to `ready` and wait half a second before  asking for the duration. Here's an example: https://codepen.io/moay/pen/Nzajqm 

Hope this helps, I'll put a 'playback-started' event to the things that we could add to afterglow.

**Comment by DoraPaula** [comment]
Thank you very much for the sample code! I'll try my best.

Your idea to add a 'playback-started' event sounds fine to me, too.

**Comment by moay** [comment]
There already is an event 'play'. Sorry for the confusion.
