### ISSUE TITLE
Why use mediaelement?

### ISSUE THREAD

**Issue by tomByrer** [moay/afterglow#82]
I see in v2 you switched to mediaelement.js.  I'm curious why, since that project hasn't accepted a new PR in 10 months, unless you are maintaining your own fork?

**Comment by moay** [comment]
We switched to medialement for several reasons:

- videoJS player setup is totally messed up. In order to have a streamlined interface, we need to have clean code. mediaelement turned out to not be much better, but a bit better it is.
- the release circles of video js are way to fast for me to keep up. They change a lot of stuff all the time and that broke the player on several updates so that we had to fix working stuff which I didn't have any energy for anymore. So I decided to go with mediaelement where the release circles are way more "stable".
- I wanted to provide expanded support for facebook video and other stuff, which wasn't easy to achieve with video js without blowing up the player with 3rd party plugins. Another pro for mediaelement.

During development, it turned out that medialement allows some new stuff and had me investigate in some issues a bit deeper than I wanted to. Currently, there are some issues with cross browser testing. As I am waiting for baby nr. 2 to be delivered and recover from sickness, development is currently stalling. PRs welcome.

**Comment by tomByrer** [comment]
Thanks for the feedback.  Yes, I'm a bit overwhelmed by VideoJS setup also....
cheers

**Comment by tomByrer** [comment]
I found this lib which has Facebook, DailyMotion, SoundCloud + more playback, clear docs, updated frequently: [CookPete's React-Player](https://cookpete.com/react-player/).  Though made with React, he does have a [standalone build](https://github.com/CookPete/react-player#standalone-player).  I found it [easy to configure](https://codepen.io/tomByrer/pen/ZwebdJ).

Plyr seems interesting also.
