### ISSUE TITLE
Re-run afterglow for Lazy Loading

### ISSUE THREAD

**Issue by spbuckle** [moay/afterglow#96]
I'm wondering if there is a way to rerun afterglow after a button is pressed to look for new videos as I have a page that uses lazy loading so some videos aren't brought into the page until a button is clicked on.

Cheers

**Comment by spbuckle** [comment]
I believe i may have found my own solution by running `window.afterglow.init();` after the click.

**Comment by besserwisser** [comment]
@spbuckle Thank you so much! You saved my weekend. Why is this not in the official documentation?

**Comment by moay** [comment]
Because this is not the perfect way to do this. It will load videos twice if they have been there before the reinit. This will be improved in future versions, if there will be any. Development is stopped for now, as I just don't have the time to support the project.

You might want to reset the loaded players manually before the init, try something like this:

`window.afterglow.players = [];`
